# Generated by Django 4.0.3 on 2022-05-04 23:29

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_wallet_balance_alter_wallet_balance_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='accountId',
            field=models.CharField(default=login.models.generateAccountId, editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
